### ISSUE TITLE
sample-config.json

### ISSUE THREAD

**Issue by Cloudore** [Supereg/homebridge-http-speaker#1]
Hey,

Just a curious guy wanting to try out a speaker in HomeKit. Not a developer myself though. Could you provide with a Sample-config.json? 

Also, I have never seen an "http" speaker, I assume that it does not provide audio through Home, just the volume and power commands, which you would bind to whatever http you want, correct?

Thanks in advance

**Comment by Supereg** [comment]
I will provide a sample config as well as a README over the weekend.

Yes, it only provides a way to send http request to some other instance. For me it was suitable to send it to my programmed IR remote for example which then controlled the actual speaker. So you probably need to develop the http endpoint yourself since it's probably not practice for modern speakers to provide an http API.
Keep in mind, that the Apple Home App doesn't support speaker, not even in the latest iOS 11 beta. HomeKit itself supports the protocol but the you cannot control it via the Home App. But other HomeKit Apps like the "Eve" App I'm using for other devices supports speakers out of the box.

**Comment by Cloudore** [comment]
Weird since speakers were discussed in the conference, I think i could work out with my rm mini a way to control my surround system which would be really nice. 

I assume they're leaving the device for the final release of iOS 11, I am also running the Beta so that really bums me out, but if I get it working on the Eve app, I assume it should automatically appear and work whenever Apple decides to make it controllable through the stock app.

I'll wait then for your updates on the README and start tinkering this weekend!

Regards!

**Comment by Supereg** [comment]
The protocol of speakers is supported since iOS 10, so yes, pretty weird. But I think speaker support for the Home App will make it with iOS 11 sooner or later. Release of the HomePod could also make sense if support isn't added until the iOS 11 GM.

Speaker appears in the Home App but it says it isn't supported. This behavior is there since iOS 10 :)
I think every third party HomeKit App will do it. Alternatively what most other people are doing is to provide a Light or Fan Service to control the Speaker, which is pretty similar to the Speaker Service. Of course the commands are different for Siri.

I hope I have some time tomorrow :)
